### ISSUE TITLE
Add wait for legionctl scale finish

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#330]
As in legionctl deploy we need to add wait for end of scale procedure.

**Comment by dsuslov** [comment]
please, eхplain in the issue description with more details why this wait is required and how it should be implemented (default value, possible configuration via cli parameters or config files, etc)

**Comment by ablatov** [comment]
The problem is that we execute legionctl scale command that just send request for scaling models instances without waiting the result of this procedure. (legion/legion/edi/deploy.py   **def scale_kubernetes(args)**). 
In the legionctl deploy command we have an awaiting mechanism of the execution (legion/legion/edi/deploy.py   **def deploy_kubernetes(args)**). 

In this task we need to implement the same mechanism for the legionctl scale command.

**Comment by kirillmakhonin** [comment]
Closed by #354
